FROM openjdk:8-jdk-alpine
ADD out/artifacts/MessageProcessorMicroservice_jar/MessageProcessorMicroservice.jar MessageProcessorMicroservice.jar
ENTRYPOINT ["java", "-jar", "MessageProcessorMicroservice.jar"]