FROM openjdk:8-jdk-alpine
ADD out/artifacts/BiddingProcessorMicroservice_jar/BiddingProcessorMicroservice.jar BiddingProcessorMicroservice.jar
ENTRYPOINT ["java", "-jar", "BiddingProcessorMicroservice.jar"]