micronaut:
  application:
    name: stare2
  server:
    port: 8082
  executors:
    consumer:
      type: FIXED
      number-of-threads: 2

kafka.bootstrap.servers: localhost:9092
rabbitmq:
  host: localhost
  port: 5672
  username: student
  password: student

